export const environment = {
  production: true,
  user_api: 'https://user.api.ecom.simecsystem.com/api/',
  catelog_api: 'https://catelog.api.ecom.simecsystem.com/api/',
  core_api: 'https://core.api.ecom.simecsystem.com/api/',
  image_api: 'https://image.api.ecom.simecsystem.com/api/',
  payment_api: 'https://payment.api.ecom.simecsystem.com/api/',
  search_api: 'https://search.api.ecom.simecsystem.com/api/',
  order_api: 'https://order.api.ecom.simecsystem.com/api/',
  notification_api: 'https://notification.api.ecom.simecsystem.com/api/',
  image_url: 'https://image.ecom.simecsystem.com/image-',
  login_url: 'https://ecom.simecsystem.com/auth/login',
  registration_url: 'https://ecom.simecsystem.com/auth/registration',
  cron_job_api: 'https://cronjob.api.ecom.simecsystem.com/api/',
  google_map_api: 'AIzaSyBJC85dIw6OmepJFtLdxiLfPSYApfXdc_g',

  payment_store_id: '',
  payment_store_password: '',
  payment_store_currency: 'BDT',
  payment_merchant_api: 'https://sandbox.sslcommerz.com/embed.min.js?',

  company_url: 'https://ecom.simecsystem.com',
  company_name: 'SIMEC-ECOM',
  company_location: {
    x: 23.870985,
    y: 90.383757,
  },
  company_phone: '01400999333',
  company_email: 'admin@ebonear.com',
};
